### ISSUE TITLE
NullPointerException on new driver upload

### ISSUE THREAD

**Issue by KMax** [semiotproject/semiot-platform#163]
Steps to reproduce:
- open the upload new driver page,
- browse a driver's jar file,
- press the upload button.

Logs:

```
apigateway_1           | 13:50:41,068 ERROR [stderr] (default task-57) javax.json.stream.JsonParsingException: Invalid token=EOF at (line no=1, column no=0, offset=-1) Expected tokens are: [CURLYOPEN, SQUAREOPEN]
apigateway_1           | 13:50:41,069 ERROR [stderr] (default task-57)  at org.glassfish.json.JsonParserImpl$NoneContext.getNextEvent(JsonParserImpl.java:240)
apigateway_1           | 13:50:41,069 ERROR [stderr] (default task-57)  at org.glassfish.json.JsonParserImpl$StateIterator.next(JsonParserImpl.java:180)
apigateway_1           | 13:50:41,069 ERROR [stderr] (default task-57)  at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:149)
apigateway_1           | 13:50:41,070 ERROR [stderr] (default task-57)  at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:98)
apigateway_1           | 13:50:41,070 ERROR [stderr] (default task-57)  at ru.semiot.platform.apigateway.config.ConfigurationDriverHandler.doGet(ConfigurationDriverHandler.java:83)
apigateway_1           | 13:50:41,071 ERROR [stderr] (default task-57)  at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
apigateway_1           | 13:50:41,071 ERROR [stderr] (default task-57)  at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
apigateway_1           | 13:50:41,071 ERROR [stderr] (default task-57)  at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:86)
apigateway_1           | 13:50:41,071 ERROR [stderr] (default task-57)  at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:130)
apigateway_1           | 13:50:41,071 ERROR [stderr] (default task-57)  at io.undertow.websockets.jsr.JsrWebSocketFilter.doFilter(JsrWebSocketFilter.java:151)
apigateway_1           | 13:50:41,072 ERROR [stderr] (default task-57)  at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
apigateway_1           | 13:50:41,072 ERROR [stderr] (default task-57)  at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132)
apigateway_1           | 13:50:41,072 ERROR [stderr] (default task-57)  at ru.semiot.platform.apigateway.IndexFilter.doFilter(IndexFilter.java:33)
apigateway_1           | 13:50:41,072 ERROR [stderr] (default task-57)  at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
apigateway_1           | 13:50:41,072 ERROR [stderr] (default task-57)  at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132)
apigateway_1           | 13:50:41,072 ERROR [stderr] (default task-57)  at org.jboss.resteasy.plugins.server.servlet.FilterDispatcher.doFilter(FilterDispatcher.java:66)
apigateway_1           | 13:50:41,073 ERROR [stderr] (default task-57)  at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
apigateway_1           | 13:50:41,073 ERROR [stderr] (default task-57)  at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132)
apigateway_1           | 13:50:41,073 ERROR [stderr] (default task-57)  at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:85)
apigateway_1           | 13:50:41,073 ERROR [stderr] (default task-57)  at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
apigateway_1           | 13:50:41,073 ERROR [stderr] (default task-57)  at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
apigateway_1           | 13:50:41,074 ERROR [stderr] (default task-57)  at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
apigateway_1           | 13:50:41,074 ERROR [stderr] (default task-57)  at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
apigateway_1           | 13:50:41,074 ERROR [stderr] (default task-57)  at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
apigateway_1           | 13:50:41,074 ERROR [stderr] (default task-57)  at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
apigateway_1           | 13:50:41,075 ERROR [stderr] (default task-57)  at io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
apigateway_1           | 13:50:41,075 ERROR [stderr] (default task-57)  at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
apigateway_1           | 13:50:41,075 ERROR [stderr] (default task-57)  at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:51)
apigateway_1           | 13:50:41,075 ERROR [stderr] (default task-57)  at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
apigateway_1           | 13:50:41,075 ERROR [stderr] (default task-57)  at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
apigateway_1           | 13:50:41,076 ERROR [stderr] (default task-57)  at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:56)
apigateway_1           | 13:50:41,076 ERROR [stderr] (default task-57)  at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58)
apigateway_1           | 13:50:41,076 ERROR [stderr] (default task-57)  at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:72)
apigateway_1           | 13:50:41,076 ERROR [stderr] (default task-57)  at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
apigateway_1           | 13:50:41,076 ERROR [stderr] (default task-57)  at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76)
apigateway_1           | 13:50:41,077 ERROR [stderr] (default task-57)  at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
apigateway_1           | 13:50:41,077 ERROR [stderr] (default task-57)  at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
apigateway_1           | 13:50:41,077 ERROR [stderr] (default task-57)  at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
apigateway_1           | 13:50:41,077 ERROR [stderr] (default task-57)  at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
apigateway_1           | 13:50:41,078 ERROR [stderr] (default task-57)  at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:282)
apigateway_1           | 13:50:41,078 ERROR [stderr] (default task-57)  at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:261)
apigateway_1           | 13:50:41,078 ERROR [stderr] (default task-57)  at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:80)
apigateway_1           | 13:50:41,078 ERROR [stderr] (default task-57)  at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:172)
apigateway_1           | 13:50:41,078 ERROR [stderr] (default task-57)  at io.undertow.server.Connectors.executeRootHandler(Connectors.java:199)
apigateway_1           | 13:50:41,078 ERROR [stderr] (default task-57)  at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:774)
apigateway_1           | 13:50:41,079 ERROR [stderr] (default task-57)  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
apigateway_1           | 13:50:41,079 ERROR [stderr] (default task-57)  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
apigateway_1           | 13:50:41,079 ERROR [stderr] (default task-57)  at java.lang.Thread.run(Thread.java:745)
apigateway_1           | 13:50:41,098 ERROR [io.undertow.request] (default task-58) UT005023: Exception handling request to /configuration/ConfigurationDriver: org.apache.jasper.JasperException: JBWEB004038: An exception occurred processing JSP page /config/ConfigurationDriver.jsp at line 10
apigateway_1           | 
apigateway_1           | 7: 
apigateway_1           | 8: <%
apigateway_1           | 9:     JsonObject jsonConfig = (JsonObject) session.getAttribute("jsonConfig");
apigateway_1           | 10:     String pid = jsonConfig.getString("semiot:driverPid");
apigateway_1           | 11:     JsonArray jsonArray = jsonConfig.getJsonArray("semiot:view");
apigateway_1           | 12:     Integer repeatbleMax;
apigateway_1           | 13:     if (jsonConfig.containsKey("semiot:maxRepeatableSchemas")) {
apigateway_1           | 
apigateway_1           | 
apigateway_1           | Stacktrace:
apigateway_1           |    at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:494)
apigateway_1           |    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:408)
apigateway_1           |    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:326)
apigateway_1           |    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:259)
apigateway_1           |    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
apigateway_1           |    at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:86)
apigateway_1           |    at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:82)
apigateway_1           |    at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
apigateway_1           |    at io.undertow.jsp.JspFileHandler.handleRequest(JspFileHandler.java:32)
apigateway_1           |    at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
apigateway_1           |    at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
apigateway_1           |    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
apigateway_1           |    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
apigateway_1           |    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
apigateway_1           |    at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:282)
apigateway_1           |    at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:261)
apigateway_1           |    at io.undertow.servlet.handlers.ServletInitialHandler.dispatchToPath(ServletInitialHandler.java:198)
apigateway_1           |    at io.undertow.servlet.spec.AsyncContextImpl$2$1.handleRequest(AsyncContextImpl.java:193)
apigateway_1           |    at io.undertow.server.Connectors.executeRootHandler(Connectors.java:199)
apigateway_1           |    at io.undertow.servlet.spec.AsyncContextImpl$2.run(AsyncContextImpl.java:190)
apigateway_1           |    at io.undertow.servlet.spec.AsyncContextImpl$6.run(AsyncContextImpl.java:464)
apigateway_1           |    at io.undertow.servlet.spec.AsyncContextImpl$TaskDispatchRunnable.run(AsyncContextImpl.java:580)
apigateway_1           |    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
apigateway_1           |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
apigateway_1           |    at java.lang.Thread.run(Thread.java:745)
apigateway_1           | Caused by: java.lang.NullPointerException
apigateway_1           |    at org.apache.jsp.config.ConfigurationDriver_jsp._jspService(ConfigurationDriver_jsp.java:68)
apigateway_1           |    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:69)
apigateway_1           |    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
apigateway_1           |    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:366)
apigateway_1           |    ... 23 more
apigateway_1           | 
```

**Comment by KMax** [comment]
https://github.com/semiotproject/semiot-platform/commit/43f450d27a06000a3b2e7900864868ab42fdc047 doesn't solve the problem. The file is not submitted to the server. The servlet receives only the file name, i.e. only the `placeholder` input is received.

Logs:

```
apigateway_1           | 06:56:56,374 DEBUG [ru.semiot.platform.apigateway.config.UploadDriverHandler] (default task-15) Part [placeholder]
apigateway_1           | 06:56:56,377 DEBUG [ru.semiot.platform.apigateway.config.UploadDriverHandler] (default task-15) Part [placeholder] fileName: null
apigateway_1           | 06:56:56,377 DEBUG [ru.semiot.platform.apigateway.config.UploadDriverHandler] (default task-15) Part [placeholder] size: 39
apigateway_1           | 06:56:56,380 DEBUG [ru.semiot.platform.apigateway.config.UploadDriverHandler] (default task-15) Part [placeholder] inputstream: netatmo-weatherstation-1.0-SNAPSHOT.jar
apigateway_1           | 06:56:56,381 ERROR [io.undertow.request] (default task-15) UT005023: Exception handling request to /UploadDriverHandler: java.lang.NullPointerException
apigateway_1           |    at ru.semiot.platform.apigateway.config.UploadDriverHandler.doPost(UploadDriverHandler.java:39)
```

**Comment by soylent-grin** [comment]
check out if this was helpful https://github.com/semiotproject/semiot-platform/commit/f7866c1a621997e6a42ba5fce022137d358550ab

**Comment by soylent-grin** [comment]
BTW is there any server-side validation of forms, coming from the client?

**Comment by KMax** [comment]
> BTW is there any server-side validation of forms, coming from the client?

Nope.
