### ISSUE TITLE
CME in Fuseki

### ISSUE THREAD

**Issue by soylent-grin** [semiotproject/semiot-platform#202]
Steps to reproduce:
1. Clean deploy of the platform
2. Set domain to actual (e.g. "https://demo.semiot.ru")
3. Install Plain lamp driver
4. Go to Explorer

Expected results: no errors, list of systems is loading

Actual result: `500` error from `/sytems/` query

Docker-compose logs on the moment of querying systems:

```
fuseki_1               | 08:29:05,500 WARN  [org.apache.jena.fuseki.Fuseki] (qtp403170294-15) [19] RC = 500 : Iterator: started at 10364, now 10370
fuseki_1               | java.util.ConcurrentModificationException: Iterator: started at 10364, now 10370
fuseki_1               |    at org.apache.jena.tdb.sys.DatasetControlMRSW.policyError(DatasetControlMRSW.java:157)
fuseki_1               |    at org.apache.jena.tdb.sys.DatasetControlMRSW.access$000(DatasetControlMRSW.java:32)
fuseki_1               |    at org.apache.jena.tdb.sys.DatasetControlMRSW$IteratorCheckNotConcurrent.checkCourrentModification(DatasetControlMRSW.java:110)
fuseki_1               |    at org.apache.jena.tdb.sys.DatasetControlMRSW$IteratorCheckNotConcurrent.hasNext(DatasetControlMRSW.java:118)
fuseki_1               |    at org.apache.jena.atlas.iterator.Iter$4.hasNext(Iter.java:303)
fuseki_1               |    at org.apache.jena.atlas.iterator.Iter$4.hasNext(Iter.java:303)
fuseki_1               |    at org.apache.jena.atlas.iterator.Iter$4.hasNext(Iter.java:303)
fuseki_1               |    at org.apache.jena.atlas.iterator.Iter.hasNext(Iter.java:908)
fuseki_1               |    at org.apache.jena.util.iterator.WrappedIterator.hasNext(WrappedIterator.java:90)
fuseki_1               |    at org.apache.jena.util.iterator.NiceIterator$1.hasNext(NiceIterator.java:105)
fuseki_1               |    at org.apache.jena.util.iterator.NiceIterator$1.hasNext(NiceIterator.java:105)
fuseki_1               |    at org.apache.jena.reasoner.rulesys.impl.TopLevelTripleMatchFrame.nextMatch(TopLevelTripleMatchFrame.java:55)
fuseki_1               |    at org.apache.jena.reasoner.rulesys.impl.LPInterpreter.run(LPInterpreter.java:328)
fuseki_1               |    at org.apache.jena.reasoner.rulesys.impl.LPInterpreter.next(LPInterpreter.java:190)
fuseki_1               |    at org.apache.jena.reasoner.rulesys.impl.Generator.pump(Generator.java:252)
fuseki_1               |    at org.apache.jena.reasoner.rulesys.impl.Generator.pump(Generator.java:239)
fuseki_1               |    at org.apache.jena.reasoner.rulesys.impl.LPBRuleEngine.pump(LPBRuleEngine.java:311)
fuseki_1               |    at org.apache.jena.reasoner.rulesys.impl.LPTopGoalIterator.moveForward(LPTopGoalIterator.java:107)
fuseki_1               |    at org.apache.jena.reasoner.rulesys.impl.LPTopGoalIterator.hasNext(LPTopGoalIterator.java:223)
fuseki_1               |    at org.apache.jena.util.iterator.WrappedIterator.hasNext(WrappedIterator.java:90)
fuseki_1               |    at org.apache.jena.util.iterator.WrappedIterator.hasNext(WrappedIterator.java:90)
fuseki_1               |    at org.apache.jena.util.iterator.FilterIterator.hasNext(FilterIterator.java:55)
fuseki_1               |    at org.apache.jena.util.iterator.WrappedIterator.hasNext(WrappedIterator.java:90)
fuseki_1               |    at org.apache.jena.util.iterator.FilterIterator.hasNext(FilterIterator.java:55)
fuseki_1               |    at org.apache.jena.sparql.engine.iterator.QueryIterTriplePattern$TripleMapper.hasNextBinding(QueryIterTriplePattern.java:135)
fuseki_1               |    at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:111)
fuseki_1               |    at org.apache.jena.sparql.engine.iterator.QueryIterRepeatApply.hasNextBinding(QueryIterRepeatApply.java:74)
fuseki_1               |    at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:111)
fuseki_1               |    at org.apache.jena.sparql.engine.iterator.QueryIterRepeatApply.makeNextStage(QueryIterRepeatApply.java:101)
fuseki_1               |    at org.apache.jena.sparql.engine.iterator.QueryIterRepeatApply.hasNextBinding(QueryIterRepeatApply.java:65)
fuseki_1               |    at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:111)
fuseki_1               |    at org.apache.jena.sparql.engine.iterator.QueryIterBlockTriples.hasNextBinding(QueryIterBlockTriples.java:63)
fuseki_1               |    at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:111)
fuseki_1               |    at org.apache.jena.sparql.engine.iterator.QueryIterProcessBinding.hasNextBinding(QueryIterProcessBinding.java:66)
fuseki_1               |    at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:111)
fuseki_1               |    at org.apache.jena.sparql.engine.iterator.QueryIterConvert.hasNextBinding(QueryIterConvert.java:58)
fuseki_1               |    at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:111)
fuseki_1               |    at org.apache.jena.sparql.engine.iterator.QueryIterDistinct.getInputNextUnseen(QueryIterDistinct.java:104)
fuseki_1               |    at org.apache.jena.sparql.engine.iterator.QueryIterDistinct.hasNextBinding(QueryIterDistinct.java:70)
fuseki_1               |    at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:111)
fuseki_1               |    at org.apache.jena.sparql.engine.iterator.QueryIteratorWrapper.hasNextBinding(QueryIteratorWrapper.java:39)
fuseki_1               |    at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:111)
fuseki_1               |    at org.apache.jena.sparql.engine.iterator.QueryIteratorWrapper.hasNextBinding(QueryIteratorWrapper.java:39)
fuseki_1               |    at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:111)
fuseki_1               |    at org.apache.jena.sparql.engine.ResultSetStream.hasNext(ResultSetStream.java:74)
fuseki_1               |    at org.apache.jena.sparql.engine.ResultSetCheckCondition.hasNext(ResultSetCheckCondition.java:59)
fuseki_1               |    at org.apache.jena.fuseki.servlets.SPARQL_Query.executeQuery(SPARQL_Query.java:319)
fuseki_1               |    at org.apache.jena.fuseki.servlets.SPARQL_Query.execute(SPARQL_Query.java:268)
fuseki_1               |    at org.apache.jena.fuseki.servlets.SPARQL_Query.executeWithParameter(SPARQL_Query.java:226)
fuseki_1               |    at org.apache.jena.fuseki.servlets.SPARQL_Query.perform(SPARQL_Query.java:201)
fuseki_1               |    at org.apache.jena.fuseki.servlets.ActionSPARQL.executeLifecycle(ActionSPARQL.java:132)
fuseki_1               |    at org.apache.jena.fuseki.servlets.SPARQL_UberServlet.executeRequest(SPARQL_UberServlet.java:332)
fuseki_1               |    at org.apache.jena.fuseki.servlets.SPARQL_UberServlet.serviceDispatch(SPARQL_UberServlet.java:293)
fuseki_1               |    at org.apache.jena.fuseki.servlets.SPARQL_UberServlet.executeAction(SPARQL_UberServlet.java:249)
fuseki_1               |    at org.apache.jena.fuseki.servlets.ActionSPARQL.execCommonWorker(ActionSPARQL.java:83)
fuseki_1               |    at org.apache.jena.fuseki.servlets.ActionBase.doCommon(ActionBase.java:79)
fuseki_1               |    at org.apache.jena.fuseki.servlets.FusekiFilter.doFilter(FusekiFilter.java:72)
fuseki_1               |    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
fuseki_1               |    at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
fuseki_1               |    at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
fuseki_1               |    at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
fuseki_1               |    at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
fuseki_1               |    at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
fuseki_1               |    at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
fuseki_1               |    at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
fuseki_1               |    at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
fuseki_1               |    at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
fuseki_1               |    at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
fuseki_1               |    at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
fuseki_1               |    at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
fuseki_1               |    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
fuseki_1               |    at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:308)
fuseki_1               |    at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:262)
fuseki_1               |    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
fuseki_1               |    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
fuseki_1               |    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
fuseki_1               |    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
fuseki_1               |    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
fuseki_1               |    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1156)
fuseki_1               |    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
fuseki_1               |    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
fuseki_1               |    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1088)
fuseki_1               |    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
fuseki_1               |    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
fuseki_1               |    at org.eclipse.jetty.server.Server.handle(Server.java:517)
fuseki_1               |    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:306)
fuseki_1               |    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
fuseki_1               |    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
fuseki_1               |    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
fuseki_1               |    at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
fuseki_1               |    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
fuseki_1               |    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
fuseki_1               |    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
fuseki_1               |    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
fuseki_1               |    at java.lang.Thread.run(Thread.java:745)
```

**Comment by garayzuev** [comment]
I ithink, it references with #183 Fuseki crashes with CME
